trigger:

  branches:
    include:
      - main
  paths:
    include:
      - 'C2-AgileDevelopmentwithAzure/project/starter_files/flask-sklearn/**'

pool:
  name: 'MySelfHostedPool'  # Use your self-hosted pool

steps:
- script: |
    python --version
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Set up Python environment'
  workingDirectory: 'C2-AgileDevelopmentwithAzure/project/starter_files/flask-sklearn'

- script: |
    pylint app.py
  displayName: 'Lint with pylint'
  workingDirectory: 'C2-AgileDevelopmentwithAzure/project/starter_files/flask-sklearn'

- script: |
    pytest
  displayName: 'Run tests'
  workingDirectory: 'C2-AgileDevelopmentwithAzure/project/starter_files/flask-sklearn'

- task: AzureWebApp@1
  inputs:
    appType: 'webAppLinux'
    appName: 'trungnq72-project2'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'