trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'C2-AgileDevelopmentwithAzure/project/starter_files/flask-sklearn/**'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv env
    source env/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'
  workingDirectory: 'C2-AgileDevelopmentwithAzure/project/starter_files/flask-sklearn'

- script: |
    pylint app.py
  displayName: 'Lint with pylint'
  workingDirectory: 'C2-AgileDevelopmentwithAzure/project/starter_files/flask-sklearn'

- script: |
    pytest
  displayName: 'Run tests'
  workingDirectory: 'C2-AgileDevelopmentwithAzure/project/starter_files/flask-sklearn'
