name: Python application test with Github Actions

# Trigger only on push events that affect files in the specified directory
on:
  push:
    paths:
      - 'C2-AgileDevelopmentwithAzure/automated_build_exercise/starter_files/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.14

    - name: Install dependencies
      run: make install
      working-directory: C2-AgileDevelopmentwithAzure/automated_build_exercise/starter_files

    - name: Lint with pylint
      run: make lint
      working-directory: C2-AgileDevelopmentwithAzure/automated_build_exercise/starter_files

    - name: Test with pytest
      run: make test
      working-directory: C2-AgileDevelopmentwithAzure/automated_build_exercise/starter_files
